import Link from "next/link";
import { ArrowRight, CheckCircle2, Headphones, Mail, MapPinned, MessageCircle, Phone, ShieldCheck } from "lucide-react";
import { Header } from "@/components/Header";
import { SearchBox } from "@/components/SearchBox";
import { FleetCarousel } from "@/components/FleetCarousel";
import { cars } from "@/lib/cars";

export default function Home() {
  return <><Header/><main>
    <section className="relative overflow-hidden bg-ink pb-28 pt-16 text-white"><div className="absolute inset-0 opacity-45" style={{ backgroundImage: "linear-gradient(105deg, rgba(0,0,0,.96), rgba(0,0,0,.8) 48%, rgba(201,21,34,.45)), url('https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1800&q=90')", backgroundSize: "cover", backgroundPosition: "center" }}/><div className="shell relative"><p className="animate-rise eyebrow mb-5 text-white/70">Location de voitures au Maroc</p><h1 className="animate-rise-delay max-w-3xl font-display text-5xl leading-[1.02] md:text-7xl">La route commence <em className="text-rust">ici.</em></h1><p className="animate-rise-delay mt-6 max-w-xl text-lg leading-relaxed text-white/80">Des véhicules fiables, une prise en charge sans attente et l&apos;essentiel du Nord du Maroc à portée de volant.</p><a href="https://wa.me/212665362442?text=Bonjour%20Mercury%20Rent%2C%20je%20souhaite%20r%C3%A9server%20une%20voiture." target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-3 rounded-full bg-[#25D366] px-6 py-4 text-sm font-bold text-white shadow-[0_12px_30px_rgba(37,211,102,.35)] transition hover:scale-105 hover:bg-[#1ebe5d]"><MessageCircle size={22} fill="currentColor"/> Réserver sur WhatsApp</a><div className="animate-rise-delay mt-10"><SearchBox/></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-sm text-white/80">{["Assistance 24h/24", "Annulation flexible", "Kilométrage illimité"].map(x => <span className="flex items-center gap-2" key={x}><CheckCircle2 size={16} className="text-rust"/>{x}</span>)}</div></div></section>
    <section className="relative -mt-10 bg-ink pb-20 text-white"><div className="shell"><div className="grid grid-cols-2 rounded-2xl border border-white/10 bg-white/5 p-6 shadow-soft md:grid-cols-4"><div><p className="font-display text-3xl">12k+</p><p className="text-sm text-white/55">clients satisfaits</p></div><div><p className="font-display text-3xl">4</p><p className="text-sm text-white/55">villes desservies</p></div><div><p className="font-display text-3xl">4.9/5</p><p className="text-sm text-white/55">avis clients</p></div><div><p className="font-display text-3xl">24/7</p><p className="text-sm text-white/55">à vos côtés</p></div></div></div></section>
    <section className="bg-ink pb-24 text-white"><div className="shell"><div className="mb-9 flex items-end justify-between"><div><p className="eyebrow text-rust">Notre flotte complète</p><h2 className="mt-2 font-display text-4xl">Choisissez votre véhicule.</h2><p className="mt-2 text-white/60">Faites glisser horizontalement pour voir toute la sélection.</p></div><Link href="/catalogue" className="hidden items-center gap-2 text-sm font-bold text-white md:flex">Voir le catalogue <ArrowRight size={16}/></Link></div><FleetCarousel cars={cars}/></div></section>
    <section id="services" className="border-t border-white/10 bg-ink py-20 text-white"><div className="shell grid gap-10 md:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow text-rust">Plus qu&apos;une location</p><h2 className="mt-3 font-display text-4xl leading-tight">Le bon service, exactement au bon moment.</h2><p className="mt-5 max-w-md text-white/65">Notre équipe locale reste accessible avant, pendant et après votre voyage.</p></div><div className="grid gap-5 sm:grid-cols-3">{[[ShieldCheck,"Transparence","Aucun frais caché."],[MapPinned,"Livraison","Tanger, Tétouan, Nador."],[Headphones,"Humain","Une équipe qui répond."]].map(([Icon,title,text]) => { const I = Icon as typeof ShieldCheck; return <div className="rounded-2xl border border-white/10 bg-white/5 p-5" key={String(title)}><I className="text-rust"/><h3 className="mt-6 font-semibold">{String(title)}</h3><p className="mt-1 text-sm text-white/60">{String(text)}</p></div> })}</div></div></section>
  </main><footer id="contact" className="relative overflow-hidden bg-ink text-white"><div className="absolute inset-0 opacity-40" style={{ backgroundImage: "linear-gradient(90deg, rgba(0,0,0,.88), rgba(0,0,0,.58)), url('https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1800&q=90')", backgroundSize: "cover", backgroundPosition: "center" }}/><div className="shell relative grid gap-10 py-16 md:grid-cols-[1.45fr_.8fr_1fr]"><div><p className="font-display text-3xl tracking-tight">mercury<span className="text-rust">.</span>rent</p><p className="mt-6 max-w-md text-lg leading-relaxed text-white/90">Des véhicules de qualité, un service humain et une location simple pour explorer le Nord du Maroc en toute confiance.</p></div><nav className="grid content-start gap-4 text-lg"><Link href="/">Accueil</Link><Link href="/catalogue">Nos voitures</Link><a href="#services">Nos services</a><a href="#contact">Contact</a></nav><div><h2 className="mb-5 text-lg font-bold uppercase tracking-wide">Contact</h2><div className="space-y-4 text-base text-white/90"><p className="flex gap-3"><MapPinned className="mt-0.5 shrink-0 text-rust" size={19}/>LOTS Riad Ahlan 2, rue 23, N°81, Tanger</p><a href="mailto:contact@mercuryrent.ma" className="flex gap-3 transition hover:text-rust"><Mail className="shrink-0 text-rust" size={19}/>contact@mercuryrent.ma</a><a href="tel:+212665362442" className="flex gap-3 transition hover:text-rust"><Phone className="shrink-0 text-rust" size={19}/>+212 665 362 442</a><a href="tel:+212539316606" className="flex gap-3 transition hover:text-rust"><Phone className="shrink-0 text-rust" size={19}/>+212 539 316 606</a></div></div></div><div className="relative border-t border-white/15"><div className="shell py-5 text-sm text-white/60">© 2026 Mercury Rent · Tous droits réservés.</div></div></footer></>;
}
