"use client";

import { FormEvent, useEffect, useState } from "react";
import { CircleDollarSign, CarFront, LockKeyhole, LogOut, UsersRound } from "lucide-react";
import { Header } from "@/components/Header";

type Booking = { id: string; name: string; phone: string; pickup: string; returnCity: string; pickupDate: string; returnDate: string; carName: string; status: string };
const demoBookings: Booking[] = [{ id: "MR-2458", name: "Yasmine El Amrani", phone: "+212 6 12 34 56 78", pickup: "Tanger", returnCity: "Tanger", pickupDate: "2026-08-12", returnDate: "2026-08-17", carName: "Dacia Duster", status: "Confirmée" }];

export default function Admin() {
  const [bookings, setBookings] = useState<Booking[]>([]);
  const [authenticated, setAuthenticated] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { setBookings(JSON.parse(localStorage.getItem("atlas-rent-bookings") ?? "[]")); setAuthenticated(localStorage.getItem("atlas-rent-admin") === "true"); }, []);
  const allBookings = [...bookings, ...demoBookings];
  function login(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); if (data.get("username") === "admin" && data.get("password") === "Delta77@") { localStorage.setItem("atlas-rent-admin", "true"); setAuthenticated(true); setError(""); } else setError("Identifiant ou mot de passe incorrect."); }
  const panel = "rounded-2xl border border-white/10 bg-[#1b292e] shadow-soft";
  if (!authenticated) return <><Header/><main className="flex min-h-[calc(100vh-80px)] items-center justify-center bg-ink px-6 py-12 text-white"><form onSubmit={login} className={`w-full max-w-md p-8 ${panel}`}><div className="flex h-12 w-12 items-center justify-center rounded-full bg-rust text-white"><LockKeyhole size={21}/></div><p className="eyebrow mt-6 text-rust">Espace sécurisé</p><h1 className="mt-2 font-display text-4xl">Administration</h1><p className="mt-3 text-sm text-white/60">Connectez-vous pour consulter les réservations.</p><label className="mt-7 block text-sm font-semibold">Identifiant<input name="username" required autoComplete="username" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-3 font-normal text-white outline-rust" placeholder="admin"/></label><label className="mt-5 block text-sm font-semibold">Mot de passe<input name="password" type="password" required autoComplete="current-password" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-3 font-normal text-white outline-rust" placeholder="••••••••"/></label>{error && <p className="mt-4 text-sm font-semibold text-red-400">{error}</p>}<button className="mt-7 w-full rounded-xl bg-rust py-4 font-bold text-white transition hover:bg-white hover:text-ink">Se connecter</button></form></main></>;
  return <><Header/><main className="min-h-[calc(100vh-80px)] bg-ink text-white"><div className="shell py-12"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow text-rust">Administration</p><h1 className="mt-2 font-display text-4xl">Tableau de bord</h1></div><div className="flex gap-3"><button onClick={() => { localStorage.removeItem("atlas-rent-admin"); setAuthenticated(false); }} className="flex items-center gap-2 rounded-xl border border-white/15 bg-white/5 px-4 py-3 text-sm font-bold"><LogOut size={16}/> Déconnexion</button><button className="rounded-xl bg-rust px-5 py-3 text-sm font-bold text-white">+ Ajouter un véhicule</button></div></div><div className="mt-9 grid gap-5 md:grid-cols-3">{[[CircleDollarSign,"42 860 DH","Revenus ce mois-ci"],[CarFront,String(bookings.length),"Nouvelles demandes"],[UsersRound,"1 284","Clients enregistrés"]].map(([Icon, number, label]) => { const I = Icon as typeof CircleDollarSign; return <div className={`${panel} p-6`} key={String(label)}><I className="text-rust"/><p className="mt-5 font-display text-3xl">{String(number)}</p><p className="text-sm text-white/55">{String(label)}</p></div>; })}</div><section className={`mt-10 p-6 ${panel}`}><div className="mb-5 flex justify-between gap-4"><div><h2 className="text-lg font-semibold">Réservations</h2><p className="mt-1 text-sm text-white/55">Les nouvelles demandes créées depuis ce navigateur s’affichent ici.</p></div><button onClick={() => { localStorage.removeItem("atlas-rent-bookings"); setBookings([]); }} className="text-sm font-bold text-rust">Effacer les tests</button></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-white/10 text-xs uppercase tracking-wider text-white/40"><tr><th className="pb-3">Référence</th><th className="pb-3">Client</th><th className="pb-3">Véhicule</th><th className="pb-3">Trajet</th><th className="pb-3">Période</th><th className="pb-3">Statut</th></tr></thead><tbody>{allBookings.map((booking) => <tr key={booking.id} className="border-b border-white/10 last:border-0"><td className="py-4 font-semibold">{booking.id}</td><td>{booking.name}<span className="block text-xs text-white/45">{booking.phone}</span></td><td>{booking.carName}</td><td>{booking.pickup} → {booking.returnCity}</td><td>{booking.pickupDate} — {booking.returnDate}</td><td><span className={`rounded-full px-3 py-1 text-xs font-bold ${booking.status === "Confirmée" ? "bg-emerald-400/15 text-emerald-300" : "bg-rust/15 text-red-300"}`}>{booking.status}</span></td></tr>)}</tbody></table></div></section></div></main></>;
}
