import Link from "next/link";
import { Luggage, MessageCircle, Settings2, Users } from "lucide-react";
import type { Car } from "@/lib/cars";

export function CarCard({ car, locale = "fr" }: { car: Car; locale?: "fr" | "en" }) {
  const english = locale === "en";
  const message = encodeURIComponent(english ? `Hello Mercury Rent, I would like to book the ${car.name}. Could you confirm availability?` : `Bonjour Mercury Rent, je souhaite réserver la ${car.name}. Pouvez-vous me confirmer la disponibilité ?`);
  return <article className="group animate-rise overflow-hidden rounded-2xl border border-white/10 bg-[#1b292e] text-white shadow-sm transition duration-300 hover:-translate-y-2 hover:border-white/25 hover:shadow-soft"><div className="relative h-48 overflow-hidden"><img src={car.image} alt={car.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-110"/>{car.badge && <span className="absolute left-4 top-4 rounded-full bg-rust px-3 py-1 text-xs font-bold text-white">{car.badge}</span>}</div><div className="p-5"><div className="mb-4"><p className="eyebrow text-[#b7c4b5]">{car.category}</p><h3 className="mt-1 text-xl font-semibold">{car.name}</h3></div><div className="mb-5 grid grid-cols-3 gap-2 border-y border-white/10 py-3 text-xs text-white/70"><span className="flex items-center gap-1"><Settings2 size={14}/>{car.transmission}</span><span className="flex items-center gap-1"><Users size={14}/>{car.seats} {english ? "seats" : "places"}</span><span className="flex items-center gap-1"><Luggage size={14}/>{car.luggage} {english ? "bags" : "sacs"}</span></div><div className="grid grid-cols-2 gap-3"><Link href={`${english ? "/en" : ""}/reservation?car=${car.id}`} className="rounded-xl bg-rust py-3 text-center text-sm font-semibold text-white transition hover:bg-white hover:text-ink">{english ? "Book" : "Réserver"}</Link><a href={`https://wa.me/212665362442?text=${message}`} target="_blank" rel="noreferrer" className="flex items-center justify-center gap-2 rounded-xl border border-[#25D366] bg-[#25D366]/10 py-3 text-sm font-semibold text-[#55e58b] transition hover:bg-[#25D366] hover:text-white"><MessageCircle size={17}/> WhatsApp</a></div></div></article>;
}
